### ISSUE TITLE
Please report this traceback: Stack creation or update failed

### ISSUE THREAD

**Issue by l1br3** [rackerlabs/ebs_snapper#42]
Simply I don't understand what to do. I can't even install ebs_snapper to AWS.
I've got an IAM role configured with all access (so I'm sure the problem does not come from here).

As told in issue #36  
```bash
git checkout alternate_regions
Previous HEAD position was bb0b303... Release v0.7.2
Branch alternate_regions set up to track remote branch alternate_regions from origin.
Switched to a new branch 'alternate_regions'
```

Then lunch the command `ebs-snapper -t eu-west-1 -V deploy --no_build 2>&1 | grep -v botocore`  

And it fails, don't understand why.

```bash
INFO:root:Creating S3 bucket ebs-snapper-234576956895 in eu-west-1 if it doesn't exist
INFO:root:Uploading files into S3 bucket
INFO:root:Uploading cloudformation.json to bucket ebs-snapper-234576956895
INFO:root:Skipping upload of ebs_snapper.zip, already up-to-date in S3
INFO:root:Creating stack from https://s3.amazonaws.com/ebs-snapper-234576956895/cloudformation.json
WARNING:root:Wait while the stack ebs-snapper-234576956895 is created.
WARNING:root:.
WARNING:root:.
WARNING:root:.
WARNING:root:.
WARNING:root:.
WARNING:root:.
WARNING:root:.
WARNING:root:.
WARNING:root:.
WARNING:root:.
Unexpected error. Please report this traceback.
Traceback (most recent call last):
  File "/home/libre/.ebs_snapper/ebs_snapper/ebs_snapper/shell.py", line 144, in main
    args.func(args)
  File "/home/libre/.ebs_snapper/ebs_snapper/ebs_snapper/shell.py", line 184, in shell_deploy
    installed_region=args[0].conf_toolregion
  File "/home/libre/.ebs_snapper/ebs_snapper/ebs_snapper/deploy.py", line 83, in deploy
    create_or_update_stack(aws_account, installed_region, ebs_bucket_name)
  File "/home/libre/.ebs_snapper/ebs_snapper/ebs_snapper/deploy.py", line 237, in create_or_update_stack
    wait_for_completion(cf_client, stack_name)
  File "/home/libre/.ebs_snapper/ebs_snapper/ebs_snapper/deploy.py", line 172, in wait_for_completion
    raise Exception('Stack creation or update failed', stack_data)
Exception: ('Stack creation or update failed', {u'StackId': 'arn:aws:cloudformation:eu-west-1:234576956895:stack/ebs-snapper-234576956895/37579030-57fc-11e7-92c6-50a68645b429', u'Description': 'Configures SNS topics and Lambda jobs for EBS Snapshot management', u'Parameters': [{u'ParameterValue': 'us-east-1', u'ParameterKey': 'WatchdogRegion'}, {u'ParameterValue': 'ebs-snapper-234576956895', u'ParameterKey': 'LambdaS3Bucket'}, {u'ParameterValue': 'rate(30 minutes)', u'ParameterKey': 'CreateScheduleExpression'}, {u'ParameterValue': 'rate(30 minutes)', u'ParameterKey': 'ReplicationScheduleExpression'}, {u'ParameterValue': 'rate(6 hours)', u'ParameterKey': 'CleanScheduleExpression'}], u'Tags': [], u'StackStatusReason': 'The following resource(s) failed to create: [FanoutReplicationSnapshotFunction, FanoutCreateSnapshotFunction, FanoutCleanSnapshotFunction, ReplicationSnapshotFunction, CleanSnapshotFunction, CreateSnapshotFunction]. . Rollback requested by user.', u'CreationTime': datetime.datetime(2017, 6, 23, 10, 10, 43, 972000, tzinfo=tzutc()), u'Capabilities': ['CAPABILITY_IAM'], u'StackName': 'ebs-snapper-234576956895', u'NotificationARNs': [], u'StackStatus': 'ROLLBACK_IN_PROGRESS', u'DisableRollback': False})
```

Note that it keep forcing a us-east-1 somewhere.

**Comment by l1br3** [comment]
I finally got it working, the rollback was not destroying the S3 bucket + I add to change the ebs-snapper name because S3 was still blocking the name of the manually destroyed S3

**Comment by martinb3** [comment]
I also got into some trouble with this as well, since S3 took over an hour after deleting a bucket in S3 standard region before letting me create one in another region.
