### ISSUE TITLE
throwing error when i deploy

### ISSUE THREAD

**Issue by Bendalam** [rackerlabs/ebs_snapper#90]
~/ebs_snapper$ ebs-snapper -V deploy --no_build 2>&1 | grep -v botocore
INFO:root:Creating S3 bucket ebs-snapper-842227021655 if it doesn't exist
INFO:root:Uploading files into S3 bucket
INFO:root:Skipping upload of cloudformation.json, already up-to-date in S3
INFO:root:Skipping upload of ebs_snapper.zip, already up-to-date in S3
INFO:root:Creating stack from https://s3.amazonaws.com/ebs-snapper-842227021655/cloudformation.json
INFO:root:Stack exists, updating stack from https://s3.amazonaws.com/ebs-snapper-842227021655/cloudformation.json
WARNING:root:No changes. Stack was not updated.
Unexpected error. Please report this traceback.
Traceback (most recent call last):
  File "/home/cloud_user/ebs_snapper/ebs_snapper/shell.py", line 144, in main
    args.func(args)
  File "/home/cloud_user/ebs_snapper/ebs_snapper/shell.py", line 182, in shell_deploy
    no_stack=args[0].no_stack
  File "/home/cloud_user/ebs_snapper/ebs_snapper/deploy.py", line 104, in deploy
    create_or_update_stack(aws_account, DEFAULT_REGION, ebs_bucket_name)
  File "/home/cloud_user/ebs_snapper/ebs_snapper/deploy.py", line 257, in create_or_update_stack
    wait_for_completion(cf_client, stack_name)
  File "/home/cloud_user/ebs_snapper/ebs_snapper/deploy.py", line 186, in wait_for_completion
    raise Exception('Stack creation or update failed', stack_data)
Exception: ('Stack creation or update failed', {u'StackId': 'arn:aws:cloudformation:us-east-1:842227021655:stack/ebs-snapper-842227021655/ffb6bae0-5b44-1
1e9-bbcb-0e366af4fd90', u'Description': 'Configures SNS topics and Lambda jobs for EBS Snapshot management', u'Parameters': [{u'ParameterValue': '256', u
'ParameterKey': 'LambdaMemoryClean'}, {u'ParameterValue': '', u'ParameterKey': 'CostCenter'}, {u'ParameterValue': 'us-east-1', u'ParameterKey': 'Watchdog
Region'}, {u'ParameterValue': 'ebs-snapper-842227021655', u'ParameterKey': 'LambdaS3Bucket'}, {u'ParameterValue': 'rate(30 minutes)', u'ParameterKey': 'C
reateScheduleExpression'}, {u'ParameterValue': 'rate(30 minutes)', u'ParameterKey': 'ReplicationScheduleExpression'}, {u'ParameterValue': '256', u'Parame
terKey': 'LambdaMemoryReplication'}, {u'ParameterValue': 'rate(6 hours)', u'ParameterKey': 'CleanScheduleExpression'}, {u'ParameterValue': '128', u'Param
eterKey': 'LambdaMemoryFanout'}, {u'ParameterValue': '256', u'ParameterKey': 'LambdaMemorySnapshot'}], u'Tags': [], u'EnableTerminationProtection': False
, u'CreationTime': datetime.datetime(2019, 4, 10, 3, 59, 11, 861000, tzinfo=tzlocal()), u'Capabilities': ['CAPABILITY_IAM'], u'StackName': 'ebs-snapper-8
42227021655', u'NotificationARNs': [], u'StackStatus': 'ROLLBACK_COMPLETE', u'DisableRollback': False, u'RollbackConfiguration': {}, u'DeletionTime': dat
etime.datetime(2019, 4, 10, 3, 59, 18, 556000, tzinfo=tzlocal())})

**Comment by martinb3** [comment]
Hi there -- could you look at the CloudFormation stack that failed to update, and tell us what the errors were that CloudFormation saw?

**Comment by Bendalam** [comment]
I am trying to install the EBS snapper as per the documentation. https://github.com/rackerlabs/ebs_snapper/blob/master/README.md#installing-the-ebs-snapper-into-an-aws-account
This is the default cloudformation.json which was already there inside the ebs_snapper directory.
And I am getting the error while running the command `$ ebs-snapper -V deploy --no_build 2>&1 | grep -v botocore`

**Comment by gdelvalle** [comment]
Looks like the stack was already deployed and the CF update was a No-op, thus  the error

```
INFO:root:Stack exists, updating stack from https://s3.amazonaws.com/ebs-snapper-842227021655/cloudformation.json
WARNING:root:No changes. Stack was not updated.
Unexpected error. Please report this traceback.
```
